<?php 
/**
 * Perform actions for sdss theme.
 */

 add_action( 'admin_menu', 'sdss_shortcodes_menu' );

 /**
 * Add shortcodes menu
**/
function sdss_shortcodes_menu() {
	add_theme_page( 'Theme Information', 'SDSS Theme Information',
		'edit_pages', __FILE__, 'sdss_shortcodes_page' );
}

/**
 * Add shortcodes page
**/
function sdss_shortcodes_page() {
?>
<div class="wrap">
<h2 >SDSS Theme Information</h2>
<h3 class="dashicons-before dashicons-menu">SDSS Menus</h3>
<table class="form-table" style="valign:top;">
<tr>
<th valign="top" rowspan="2">Names:</th>
<td>Menu names should begin and end with a slash, e.g. /dr12/, /dr12/algorithms/, /surveys/.</td>
</tr>
<tr>
<td>Menu names should be assigned according to the Parent Page you want them to show up on. For example: 
<ul>
<li>the menu /dr12/ will show up on all pages that start with /dr12/ including /dr12/, /dr12/data_access/, /dr12/spectro/, etc.</li>
<li>/dr12/spectro/ will show up on /dr12/spectro/ and all pages below, such as /dr12/spectro/overview/.</li>
</ul>
</td>
</tr>
<tr>
<th valign="top" rowspan="3">Locations:</th>
<td>Menu locations that start with Secondary Tier will display below the primary navigation.</td>
</tr>
<tr>
<td>Menu locations that start with Sidebar will display on the right hand sidebar. The order (first, second, etc) is not important.</td>
</tr>
<tr>
<td>Menus that start with CPT will display in the sidebar for that Custom Post Type. These may need to be added in the backend as needed.</td>
</tr>
<tr>
<th valign="top" rowspan="3">CSS Styles:</th>
<td><strong>indent</strong>: Indents a sidebar menu item with the CSS style 'indent'.
</td>
</tr>
<tr>
<td><strong>heading</strong>: Create a non-navigable item with a bold font with the CSS style 'heading'.</td>
</tr>
<tr>
<td><strong>disable</strong>: Use the style 'disable' to disable any menu item.</td>
</tr>
<tr>
<th valign="top">Menus for Custom Post Types [CPT]</th>
<td>To add a menu to a custom post type, the menu must be called cpt_"cpt-name", and added to the theme initialization file, init.php by the web developer. Use the menus admin interface to assign a menu to that cpt (menus can be assigned to more than one location). </td>
</tr>
</table>

<h3 class="dashicons-before dashicons-media-text">Boilerplate Shortcodes</h3>
<p>Boilerplate shortcodes allow you to input standardized text into page or post content. This is very useful, e.g. for licensing information. </p>
<table class="form-table">
<tr valign="top">
<th>[sdss_boilerplate which="..."]</th>
<td>Use this shortcode to insert boilerplate into a Page or Post content area. </td>
</tr>
<tr valign="top">
<th>Acknowledgements</th>
<td>[sdss_boilerplate which="acknowledgements"]</td>
</tr>
<tr valign="top">
<th>TeX Acknowledgements</th>
<td>[sdss_boilerplate which="tex-acknowledgements"]</td>
</tr>
<tr valign="top">
<th>SDSS Institional Affiliations</th>
<td>[sdss_boilerplate which="affiliations"]</td>
</tr>
<tr valign="top">
<th>
SDSS Options page
</th>
<td>
View/Edit the boilerplate content on this page. 
</td>
</tr>
<tr valign="top">
<th>
WCK Option Fields Creator > Boilerplate > Edit
</th>
<td>Add new boilerplate to use in the website on this page. <br>
When you give your boilerplate a <strong>Field Title</strong>, a <em>slug</em> will automatically be generated by transforming it to lowercase and replacing all spaces to "-" and removing all special characters. Use the <em>slug</em> as the boilerplate argument for which="slug". <br>
For example, if you create a new boilerplate called <strong>Creative License</strong>, its slug will be <em>creative-license</em>, and the shortcode you would use to add it to your page would be <br/>
[sdss_boilerplate which="creative-license"]
</td>
</tr>
</table>

<h3 class="dashicons-before dashicons-admin-tools">Formatting Shortcodes</h3>
<p>The following shortcodes are currently supported:</p>
<dl><dt>Table of Contents: <br>[SDSS_TOC]</dt>
<dd><em>This currently doesn't not work well and should be replaced with a different tool</em>>Create a table of Contents from h2, h3, h4 selectors. Optionally specify which <strong>selectors</strong> to use, whether to start out <strong>open</strong> (default is closed), and whether to <strong>clear</strong> (display subsequent content below instead of to the right).<br><br>
<strong>Examples of usage: </strong>
<ul>
<li>[SDSS_TOC]: default. Uses h2, h3, h4 (default) selectors. Initially closed. Wrap following text to the right. </li>
<li>[SDSS_TOC selectors="h2"]: Use only h2 selector. Initially closed. Wrap following text to the right. </li>
<li>[SDSS_TOC selectors="h2,h3" open]: Use h2 and h3 selectors. Initially open. Wrap following text to the right. </li>
<li>[SDSS_TOC clear]: Use default selectors. Initially closed. Subsequent content displays below TOC. </li>
</ul>
<strong>Notes: </strong>
<ul>
<li>Do not include spaces in the list of selectors.</li>
<li>Place this directly below a heading and in front of and on same line as a paragraph. If precedes a paragraph, use 'clear' option.</li>
</ul>
</dd>
<dt>SDSS Gallery: [SDSS_GALLERY]</dt>
<dd>Show SDSS images in a gallery. Skip images tagged as NO-SHOW.
</dd>
<dt>To Top Link: [SDSS_TOTOP]</dt>
<dd>Displays an up arrow and link to top of page. Useful for long pages. Place above headings or at and of page.
</dd>
<dt>PANELS can be nested<br>
Story panel: <br>
[SDSS_STORY]<br>
[/SDSS_STORY]</dt>
<dd>Put a title above and a frame around a story. Specify # columns.
</dd>
<dt>Figure panel: <br>
[SDSS_FIGURE]<br>
[/SDSS_FIGURE]</dt>
<dd>Put a title above and frame around and a caption below a figure. Specify # columns.
</dd>
</dl>
</div>
<?php
}


/* Add shortcodes 
 *	[SDSS_TOC selectors="h2, h3"] Shows a table of contents containing all h2 and h3 selectors
 *	[SDSS_TOTOP] Shows an up arrow and "Back to top" that takes you to the top of the current page.
 */
add_shortcode('SDSS_TOC','sdss_toc_inject');
add_shortcode('SDSS_TOTOP','sdss_totop_inject');
add_shortcode('SDSS_TODO','sdss_todo_showhide');
add_shortcode('SDSS_GALLERY','sdss_gallery');
add_shortcode('SDSS_FIGURE','sdss_figure_style');
add_shortcode('SDSS_GROUP','sdss_group_style');
add_shortcode('SDSS_STORY','sdss_story_style');
add_shortcode('SDSS_VIDEO','sdss_video_style');
add_shortcode('SDSS_CLEAR','sdss_clear');
add_shortcode('SDSS_SUMMARY','sdss_summary_style');

add_shortcode('sdss_boilerplate','sdss_boilerplate');

/**
 * Wrap a story in a panel, align left or right, set max width and title
 **/
function sdss_clear(  ){
	return '<div class="clearfix"></div>';
}

/*
 * Put in a button that takes you to the top of the page.
 */
function sdss_totop_inject(  ) {

	$injection =  sdss_clear() . '<div class="totop-wrapper" >'."\n";
	$injection .= '<span class="well well-sm" >'."\n";
	$injection .= '<a href="#">'."\n";
	$injection .= '<span class="glyphicon glyphicon-circle-arrow-up">'."\n";
	$injection .= '</span></a><span><a href="#">Back to Top</a></span>'."\n";
	$injection .= '</span></div>' . sdss_clear();

	return $injection;	
}

/*
 * Show the TODO when WP_DEBUG is true. Hide otherwise.
 */
function sdss_todo_showhide( $attr, $content = null ) {
	
	if (empty($content)) return; //no CONTENT

	$injection = ( defined('WP_DEBUG') && constant( 'WP_DEBUG' ) === true ) ?  '<div class="show" >' . "\n" : '<div class="hide" >' . "\n";
	$injection .= '<div class="bg-todo">' . do_shortcode($content) . '</div>' . "\n" . '</div>';
	return $injection;	
}

/**
 * Wrap a story in a panel, align left or right, set max width and title
 **/
function sdss_video_style( $attr, $content = null ){

	if (empty($content)) $content = "No Content"; //no video?

	$num_columns =  (empty($attr['columns'])) ? 12 : intval($attr['columns']) ;
	$video_columns =  ' col-md-' . $num_columns . ' ' . ' col-xs-12 ' ;
	$video_align = (empty($attr['align'])) ? '' : ' align' . esc_attr($attr['align']) . ' ' ;
	$video_title = (empty($attr['title'])) ? '' : '<div class="panel-heading">' . $attr['title'] . '</div>' ;
	$video_content = '<div class="responsive-video"><iframe src="' . $content . '" width="100%" height="auto" frameborder="0" allowfullscreen></iframe></div>';
	$video_content =  '<div class="panel-body">' . $video_content . '</div>';
	$video_content =  '<div class="panel panel-default sdss-wrapper ' . $video_align . $video_columns . '">' . $video_title . $video_content . '</div>';
	
	return $video_content;
}

/** 
 * Wrap a group in a panel, align left or right, set max width and title
 **/
function sdss_group_style( $attr, $content = null ){
	
	if (empty($content)) $content = "No Content"; //no group?
	
	//formatting width and alignment
	$num_columns =  (empty($attr['columns'])) ? 12 : intval($attr['columns']) ;
	$group_columns =  ' col-md-' . $num_columns . ' col-xs-12 ' ;	
	$group_align = (empty($attr['align'])) ? '' : ' align' . esc_attr($attr['align']) . ' ' ;
	
	//title/heading - can contain html like <h3></h3> etc
	$group_title = (empty($attr['title'])) ? '' : '<div class="panel-heading">' . $attr['title'] . '</div>' . "\n" ;

	//content
	$group_content = (!empty($content)) ? '<div class="panel-body">' . "\n" . do_shortcode($content) . '</div>' . "\n" : '' ;

	//wrap bodies 
	$group_content =  '<div class="panel panel-default sdss-group " >' . "\n" . $group_title . $group_content . '</div>' . "\n" ; 
	
	//assemble in wrapper
	$group_content = '<div class="sdss-group-wrapper ' . $group_align . $group_columns  . '" >' . "\n" . $group_content . '</div>' . "\n";
	return $group_content;
	
}

/** 
 * Wrap a story in a panel, align left or right, set max width and title
 **/
function sdss_story_style( $attr, $content = null ){
	
	if (empty($content)) $content = "No Content"; //no story?
	
	//formatting width and alignment
	$num_columns =  (empty($attr['columns'])) ? 6 : intval($attr['columns']) ;
	$story_columns =  ' col-md-' . $num_columns . ' col-xs-12 ' ;	
	$story_align = (empty($attr['align'])) ? '' : ' sdss-story-' . esc_attr($attr['align']) . ' ' ;
	
	//title/heading - can contain html like <h3></h3> etc
	$story_title = (empty($attr['title'])) ? '' : '<div class="panel-heading">' . $attr['title'] . '</div>' . "\n"  ;

	//content
	$story_content = (!empty($content)) ? '<div class="panel-body">' . "\n"  . do_shortcode($content) . '</div>' . "\n"  : '' ;

	//wrap bodies 
	$story_content =  '<div class="panel panel-default sdss-story " >' . "\n"  . $story_title . $story_content . '</div>' . "\n"; 
	
	//assemble in wrapper
	$story_content = '<div class="sdss-wrapper ' . $story_align . $story_columns  . '" >' . "\n"  . $story_content . '</div>' . "\n" ;
	return $story_content;
	
}

/** 
 * Wrap a summary in a panel, align left or right, set max width and title
 **/
function sdss_summary_style( $attr, $content = null ){
	
	if (empty($content)) $content = "No Content"; //no story?
	
	//content
	//$summary_content = '<div class="sdss-summary col-xs-11 col-xs-offset-0 col-md-10 col-md-offset-1">' . do_shortcode($content) . '</div>' ;
	$summary_content = '<div>' . do_shortcode($content) . '</div>' ;
	$summary_content .= sdss_clear() ;
	
	return $summary_content;
	
}

function sdss_figure_style( $attr, $content = null ){
	
	//allow image to be called src
	$thisimage = (!empty($attr['image'])) ? $attr['image'] : ((!empty($attr['src'])) ? $attr['src'] : '') ;
		
	//allow link to be called href
	$thislink = (!empty($attr['link'])) ? $attr['link'] : ((!empty($attr['href'])) ? $attr['href'] : '') ;
	
	//set alignment, number of columns and alt text
	$num_columns =  (empty($attr['columns'])) ? 6 : intval($attr['columns']) ;
	$fig_columns =  ' col-md-' . $num_columns . ' col-xs-12 ' ;	
	$fig_align = (empty($attr['align'])) ? '' : ' sdss-fig-' . esc_attr($attr['align']) . ' ' ;
	$fig_alt = (!empty($attr['alt'])) ? ' alt="' . esc_attr($attr['alt']) . '" ' : ' alt="' . esc_attr($content) . '" ';
	
	//wrap title
	$fig_title = (empty($attr['title'])) ? '' : '<div class="panel-heading">' . $attr['title'] . '</div>' ;
	
	//set up image tag
	$fig_content = (!empty($thisimage)) ? '<img class="img-responsive" src="' . $thisimage . '" '  . $fig_alt .  '/>' :  '' ;
	$fig_content = (!empty($thislink)) ? '<a href="' . $thislink . '" target="_blank" >' . $fig_content . '</a>' : $fig_content ;
	
	//wrap bodies 
	$fig_content = '<div class="panel-body">' . $fig_content . '</div>' ;
	$fig_caption = (!empty($content)) ? '<div class="panel-body caption">' . $content . '</div>' : '' ;
	$fig_content = '<div class="panel panel-default sdss-figure" >' . $fig_title . $fig_content  . $fig_caption  . '</div>' ; 
	
	//assemble in wrapper
	$fig_content = '<div class="sdss-wrapper ' . $fig_align . $fig_columns . '">' . $fig_content . '</div>';
	return $fig_content;
	
}

function sdss_toc_inject( $attr = array()){

	if (empty($attr['selectors'])) {
		$selectors = '' ;
	} else {
		$selectors = explode(",",$attr['selectors']);
		foreach ($selectors as $thisselector) $thisselector = trim($thisselector);
		$selectors = ' class="toc-' . implode("-",$selectors) . '" ';
	}
	
	//set up string variables for opened/closed table of contents, and clear afterwards
	//$open = (in_array('open',$attr)) ? array( '' , 'in' ) : array( 'collapsed' , '') ;
	//$clear = (in_array('clear',$attr)) ? '<span class="clearfix"></span>' : '' ;
	$open = (empty($attr['open'])) ? array( 'collapsed' , '') : array( '' , 'in' ) ;
	$injection = '<div id="toc-wrapper">'."\n";
	$injection .= '<div class="tocify-title">'."\n";
	$injection .= '<a class="accordion-toggle ' . $open[0] . ' " data-toggle="collapse" href="#toc-body" ';
	$injection .= 'aria-expanded="true" aria-controls="toc-body">Table&nbsp;of&nbsp;Contents</a>'."\n";
	$injection .= '</div>'."\n";
	$injection .= '<div id="toc-body" class="collapse ' . $open[1] . ' ">'."\n";
	$injection .= '<div id="toc"' . $selectors . ">";
	$injection .= '</div></div></div>';

	return $injection;
	
} 

/*
 * Show the SDSS Option (as defined on SDSS Options page on the admin menu)
 */
function sdss_boilerplate( $attr = array() ) {
	
	if ( empty( $attr[ 'which' ] ) ) return "";
	$which = $attr[ 'which' ];

	if ( strcmp( 'affiliations' , $which ) === 0 ) {
		return sdss_get_project_affiliations( true , 4 );
	}
	
	$options  = get_option( 'sdss_boilerplate' );
	
	$injection = $options[0][$which];
	
	return $injection;	
}

?>
